# Generated by Django 5.1.6 on 2025-02-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_rename_numero_serie_bem_rfid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='rfid_id',
            field=models.CharField(max_length=100),
        ),
    ]
