# Generated by Django 5.1.6 on 2025-02-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_alter_movimentacao_rfid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='rfid_id',
            new_name='rfid',
        ),
    ]
