# Generated by Django 5.1.6 on 2025-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_rename_rfid_id_movimentacao_rfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='data',
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='rfid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
