# Generated by Django 5.1.6 on 2025-02-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_remove_movimentacao_data_alter_movimentacao_rfid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7),
        ),
    ]
