# Generated by Django 5.1.6 on 2025-02-22 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_alter_movimentacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
